Update ss-rules

diff --git a/trunk/user/shadowsocks/scripts/ss-rules b/trunk/user/shadowsocks/scripts/ss-rules
--- a/trunk/user/shadowsocks/scripts/ss-rules
+++ b/trunk/user/shadowsocks/scripts/ss-rules
@@ -262,5 +262,7 @@ elif [ "$TPROXY" = 2 ] ; then
 fi
 
 flush_rules && ipset_init && ipt_nat && ipt_mangle && export_ipt_rules
-[ "$?" = 0 ] || loger 3 "Start failed!"
-exit $?
+RET=$?
+[ "$RET" = 0 ] && loger 5 "Start Success!" || loger 3 "Start failed!"
+exit $RET
+
